project_id = "grdolasawzsrwuqhpheu"

[functions.send-experience-confirmation]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-custom-order-email]
verify_jwt = false

[functions.create-custom-order-payment]
verify_jwt = false

[functions.verify-custom-order-payment]
verify_jwt = false

[functions.verify-experience-payment]
verify_jwt = false